#ifndef CONSTANTS
#define CONSTANTS

#define NAME_SIZE 30
#define PASSWORD_SIZE 35
#define MAX_TRANSACTIONS 10
#define FEEDBACK_SIZE 10
#define LOAN_SIZE 10
#define SALT "10"

#define INITIAL_PROMPT \
    "\nLog in as:\n\
1. Customer\n\
2. Bank Employee\n\
3. Manager\n\
4. Admin\n\
5. Exit\n\
"

#define EMPLOYEE_LOGIN_PAGE "Welcome Employee! Enter your details to log in\n"
#define CUSTOMER_LOGIN_PAGE "Welcome Customer! Enter your details to log in\n"
#define MANAGER_LOGIN_PAGE "Welcome Manager! Enter your details to log in\n"
#define ADMINISTRATOR_LOGIN_PAGE \
    "Welcome Administrator! Enter your details to log in\n"

#define CUSTOMER_MENU \
    "CUSTOMER MENU\n\
1. View account balance\n\
2. Deposit money\n\
3. Withdraw money\n\
4. Transfer funds\n\
5. Apply for Loan\n\
6. View Transaction History\n\
7. Add feedback\n\
8. Change password\n\
9. Logout\n\
"

#define EMPLOYEE_MENU \
    "EMPLOYEE MENU\n\
1. Add new customer\n\
2. Modify customer details\n\
3. View Assigned Loan\n\
-- Reject Loan\n\
-- Accept Loan\n\
4. View Customer Transactions\n\
5. Change password\n\
6. Logout\n\
"

#define MANAGER_MENU \
    "MANAGER MENU\n\
1. Activate customer account\n\
2. Deactivate customer account\n\
3. Assign loan application to employee\n\
4. Review customer feedback\n\
5. Change password\n\
6. Logout\n\
"

#define ADMINISTRATOR_MENU \
    "ADMINISTRATOR MENU\n\
1. Add new bank employee\n\
2. Modify customer details\n\
3. Modify employee details\n\
4. Manage user role\n\
5. Change password\n\
6. Logout\n\
"
#define SUCCESS "Operation was successfull"

#define WHICH_USER "Enter their username:"
#define WHICH_DETAIL \
    "What do you want to modify:\n\
1: Name\n\
2: Age\n\
3: Gender\n\
4: Done"

#define USERNAME "Enter your username:"
#define PASSWORD "Enter your password:"
#define NEW_PASSWORD "Enter new password:"

#define ASK_NAME "Enter name:"
#define ASK_AGE "Enter age:"
#define ASK_PASSWORD "Enter password:"
#define ASK_BALANCE "Enter Balance:"
#define ASK_GENDER \
    "Enter gender:\n\
M: Male\n\
F: Female\n\
O: Others"
#define ASK_ROLE \
    "Enter Employee role:\n\
1: Bank Employee\n\
2: Manager\n"
#define ASK_AMOUNT "Enter the amount "
#define ASK_LOAN_ID "\nEnter loan ID: "
#define ASK_EMPLOYEE_ID "\nEnter Employee id: "

#define AUTOGEN_USERNAME "The autogenerated username is:"
#define AUTOGEN_PASSWORD "The autogenerated password is:"

#define BALANCE "Your account balance is: \u20B9"
#define WITHDRAW_AMOUNT "Enter the amount you want to withdraw: "
#define DEPOSIT_AMOUNT "Enter the amount you want to deposit: "
#define TRANSFER_AMOUNT "Enter the amount you want to Transfer: "
#define WHOM_TO_TRANSFER \
    "Enter the username to whom you want to transfer the funds"
#define INSUFFICIENT_BALANCE \
    "Balance is not sufficient, please try with a lower amount"

#define INVALID_USERNAME "You entered wrong username"
#define INVALID_USERID "You entered wrong user-id"
#define INVALID_PASSWORD "You entered wrong password"
#define INVALID_ENTRY "Your input is invalid. Please select from given options"

#define CUSTOMER_FILE "./Records/customer.txt"
#define EMPLOYEE_FILE "./Records/employee.txt"
#define TRANSACTION_FILE "./Records/transaction.txt"
#define LOAN_FILE "./Records/loan.txt"

#define TRANSACTION_DETAIL "Transaction details:\n"

#define ADMINISTRATOR_USERNAME "Himanshu"
#define ADMINISTRATOR_PASSWORD "10vrzSg43HfWI"  // 123456

#define MAX_REACHED \
    "Employee reached maximum capacity. Try with some other Employee"
#define ALREADY_APPLIED " You have already applied for loan"
#define INACTIVE "Your account is in-active at the moment"
#define TO_PROCEED "Press any key to proceed (Enter to logout)"
#define LOGOUT "Logging off! Have a nice day.$"
#define EXIT "Exiting from the server.$"

#endif
